### ISSUE TITLE
Problem when generating normal surface

### ISSUE THREAD

**Issue by visionbike** [hlwang1124/NIM#1]
Dear author,

When apply the NIM module, it cannot produce fully normal surface from my own depth image. The applied depth image have size of 1280x720. However, when visualizing normal surface the code just generate only a partial normal surface (the bottom part) therefore I cannot evaluate the normal surface.

Following is the generated normal surface.

![NIM](https://user-images.githubusercontent.com/33955657/125051821-eafc6f00-e0d5-11eb-8f63-317efa5ec6de.png)

Hope hearing from you soon.

Thank you for sharing your work.

**Comment by hlwang1124** [comment]
Hi, @visionbike . I suggest you comment out Lines 85-86 in `demo.py`.

**Comment by visionbike** [comment]
Great! It works! Thank you so much.
